name: autth_injustice_app
description: "WhereIF campus events and navigation app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cloud_firestore: ^6.5.0
  auto_injector: ^2.1.1
  equatable: ^2.0.8
  firebase_auth: ^6.4.0
  firebase_core: ^4.7.0
  go_router: ^17.2.2
  google_fonts: ^8.1.0
  google_sign_in: ^7.2.0
  image_picker: ^1.2.3
  intl: ^0.20.2
  signals_flutter: ^6.3.0
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2
  flutter_svg: ^2.0.10
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  webview_flutter: 4.14.1
dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/institutions/ifpr-pgua/branding/
    - assets/institutions/ifpr-pgua/event_banners/
    - assets/institutions/ifpr-pgua/map/campus_exterior_standard.glb
    - assets/institutions/ifpr-pgua/map/campus_map.json
    - assets/institutions/ifpr-pgua/map/viewer/index.html
    - assets/institutions/ifpr-pgua/map/viewer/viewer.bundle.js
    - assets/institutions/ifpr-pgua/map/viewer/viewer_config.js
    - assets/institutions/ifpr-pgua/map/viewer/LICENSE-three.txt
